// Shared TypeScript types for job listings and applications

export type ApplicationStatus =
  | 'detected' // Extension found a job form
  | 'filling' // Currently autofilling
  | 'filled' // Form filled, awaiting review
  | 'reviewing' // User is reviewing
  | 'applied' // Successfully submitted
  | 'skipped' // User skipped this job
  | 'failed' // Error during fill/apply
  | 'saved' // Saved for later

export type JobPlatform =
  | 'linkedin'
  | 'indeed'
  | 'greenhouse'
  | 'lever'
  | 'workday'
  | 'ashby'
  | 'smartrecruiters'
  | 'unknown'

export interface JobListing {
  id: string // UUID generated by extension
  platform: JobPlatform
  url: string
  title: string
  company: string
  location: string
  salary?: string
  description: string // Full job description text
  requirements?: Array<string>
  detectedAt: string // ISO timestamp
}

export interface JobApplication {
  id: string
  job: JobListing
  status: ApplicationStatus
  appliedAt?: string // ISO timestamp
  notes?: string
  aiGeneratedAnswers?: Record<string, string> // fieldId → answer
  coverLetter?: string
  error?: string
}

export type JobApplicationSummary = Pick<
  JobApplication,
  'id' | 'status' | 'appliedAt' | 'notes'
> & {
  jobTitle: string
  company: string
  platform: JobPlatform
  url: string
}
